config/routes.rb
Busybody::Application.routes.draw do
  get "users/new"

  get "pages/home"

  get "pages/contact"

  get "pages/about"

  resources :buzzs

  resources :bees

  resources :microposts

  resources :stores

  resources :users

  get "say/hello"

  get "say/goodbye"

  get "welcome/index"
  
  match '/signup', :to => 'users#new'

  match '/contact', :to => 'pages#contact'

  match '/about', :to => 'pages#about'
  
  match '/help', :to => 'pages#help'

  root :to => 'pages#home'

   

  root :to => 'welcome#index'

end

app/models/buzz.rb
class Buzz < ActiveRecord::Base
	belongs_to :bee
	
	validates :content, :length => { :maximum => 140 }
end

app/controllers/buzzs_controller.rb
class BuzzsController < ApplicationController
  # GET /buzzs
  # GET /buzzs.json
  def index
    @buzzs = Buzz.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buzzs }
    end
  end

  # GET /buzzs/1
  # GET /buzzs/1.json
  def show
    @buzz = Buzz.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @buzz }
    end
  end

  # GET /buzzs/new
  # GET /buzzs/new.json
  def new
    @buzz = Buzz.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @buzz }
    end
  end

  # GET /buzzs/1/edit
  def edit
    @buzz = Buzz.find(params[:id])
  end

  # POST /buzzs
  # POST /buzzs.json
  def create
    @buzz = Buzz.new(params[:buzz])

    respond_to do |format|
      if @buzz.save
        format.html { redirect_to @buzz, notice: 'Buzz was successfully created.' }
        format.json { render json: @buzz, status: :created, location: @buzz }
      else
        format.html { render action: "new" }
        format.json { render json: @buzz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buzzs/1
  # PUT /buzzs/1.json
  def update
    @buzz = Buzz.find(params[:id])

    respond_to do |format|
      if @buzz.update_attributes(params[:buzz])
        format.html { redirect_to @buzz, notice: 'Buzz was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @buzz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buzzs/1
  # DELETE /buzzs/1.json
  def destroy
    @buzz = Buzz.find(params[:id])
    @buzz.destroy

    respond_to do |format|
      format.html { redirect_to buzzs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/buzzs_helper.rb
module BuzzsHelper
end

app/views/buzzs/_form.html.erb
<%= form_for(@buzz) do |f| %>
  <% if @buzz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buzz.errors.count, "error") %> prohibited this buzz from being saved:</h2>

      <ul>
      <% @buzz.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buzzs/edit.html.erb
<h1>Editing buzz</h1>

<%= render 'form' %>

<%= link_to 'Show', @buzz %> |
<%= link_to 'Back', buzzs_path %>

app/views/buzzs/index.html.erb
<h1>Listing buzzs</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @buzzs.each do |buzz| %>
  <tr>
    <td><%= buzz.content %></td>
    <td><%= buzz.user_id %></td>
    <td><%= link_to 'Show', buzz %></td>
    <td><%= link_to 'Edit', edit_buzz_path(buzz) %></td>
    <td><%= link_to 'Destroy', buzz, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Buzz', new_buzz_path %>

app/views/buzzs/new.html.erb
<h1>New buzz</h1>

<%= render 'form' %>

<%= link_to 'Back', buzzs_path %>

app/views/buzzs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @buzz.content %>
</p>

<p>
  <b>User:</b>
  <%= @buzz.user_id %>
</p>


<%= link_to 'Edit', edit_buzz_path(@buzz) %> |
<%= link_to 'Back', buzzs_path %>